### ISSUE TITLE
Build xonsh shell binary using Nuitka

### ISSUE THREAD

**Issue by jonathanslenders** [xonsh/xonsh#2895]
Just wondering... did anyone ever try to build Xonsh using Nuitka?
I noticed that for some CLI applications, building it with Nuitka gives a statically linked binary with an improved start-up time as well.

I tried it as follows:
```sh
python -O -m nuitka --follow-imports ./scripts/xonsh 
```
This creates a "xonsh.bin" executable of about 28M.
I works mostly here, but doesn't give me the prompt_toolkit shell. I tried it for pyvim, where it works great.

@scopatz ?

You can close this issue. I only wanted to share the idea.

**Comment by gforsyth** [comment]
Hey @jonathanslenders -- thanks for the suggestion!  I think there's probably a bunch of users who could benefit from this.  I'll try to see if I can get it to start up the `prompt_toolkit` backend.

**Comment by scopatz** [comment]
Wow, it doesn't seem to like lazyasd at all

**Comment by anki-code** [comment]
After a year I've tried to run this again:
```
python3 -O -m nuitka --follow-imports /xonsh/scripts/xonsh
```
Yup, lazyasd tells us:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/xonsh/main.py", line 404, in main
    args = premain(argv)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/main.py", line 357, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/main.py", line 283, in start_services
    execer = Execer(
  File "/usr/local/lib/python3.6/dist-packages/xonsh/execer.py", line 63, in __init__
    load_builtins(execer=self, ctx=xonsh_ctx)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/built_ins.py", line 1300, in load_builtins
    builtins.__xonsh__.load(execer=execer, ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/built_ins.py", line 1372, in load
    self.env = Env(default_env())
  File "/usr/local/lib/python3.6/dist-packages/xonsh/environ.py", line 1770, in default_env
    ctx = dict(BASE_ENV)
  File "/usr/local/lib/python3.6/dist-packages/xonsh/lazyasd.py", line 54, in __getattribute__
    obj = self._lazy_obj()
  File "/usr/local/lib/python3.6/dist-packages/xonsh/lazyasd.py", line 53, in __getattribute__
    return super().__getattribute__(name)
AttributeError: 'method-wrapper' object has no attribute '_lazy_obj'
Xonsh encountered an issue during launch
Failback to /bin/sh
# 

```

**Comment by anki-code** [comment]
May be lazyasd is not needed in nuitka bin and it could be switched off?

**Comment by scopatz** [comment]
Yeah, we could try to do that

**Comment by scopatz** [comment]
Is there anyway to know that nukita is running?

**Comment by scopatz** [comment]
I have opened https://github.com/Nuitka/Nuitka/issues/650

**Comment by anki-code** [comment]
_Originally posted by @anki-code in https://github.com/Nuitka/Nuitka/issues/650#issuecomment-605450552_

> I've found a way how to build static linked binary portable python app using Nuitka. Docker example you can find in https://github.com/xxh/xxh-portable . The main feature is avoiding using glibc and use static linked musle libc instead. It works on many linux.
>
>If anybody can suggest workaround for the lazyasd exception I'll be happy to try build xonsh using this technique.

**Comment by anki-code** [comment]
I've made a try to disable lazyasd and have some success with xonsh 0.9.24 on Linux.

1. Added `__new__(self, load, ctx, name)` to `LazyObject` class that returned just `d["load"]()`.
2. The lazy imports in `lazyimps.py` replaced to the ordinary import.
3. The code should be reordered in a few scripts because without "lazy" the order has meaning.

After these steps the command that described in the previous messages was built the binary and the xonsh could be run without errors by `XONSH_DEBUG=1 ./xonsh.bin` (debug is needed to avoid amalgamate). 

So this means that if we would have an alternative way to implement Nuitka-compatible logic of lazy loading this was already allows to run xonsh binary in debug mode.

**Comment by anki-code** [comment]
hi! During last days I dive deeper into the error that we got when try to run xonsh binary that created by Nuitka:

>  File "/usr/local/lib/python3.6/dist-packages/xonsh/environ.py", line 1770, in default_env
>    ctx = dict(BASE_ENV)
>  File "/usr/local/lib/python3.6/dist-packages/xonsh/lazyasd.py", line 54, in __getattribute__
>    obj = self._lazy_obj()
>  File "/usr/local/lib/python3.6/dist-packages/xonsh/lazyasd.py", line 53, in __getattribute__
>    return super().__getattribute__(name)
> AttributeError: 'method-wrapper' object has no attribute '_lazy_obj'

After tens of experiments I've found that the call:
 
```python
VAR = LazyObject(lambda: {"a":42}, globals(), 'VAR')
dict(VAR)
``` 
is working in Python but is not working in xonsh binary from Nuitka.

The issue is in `dict(...)` constructor logic. Unlike most of `LazyObject` use cases the dict constructor makes the series of calls to `LazyObject`. During these calls `LazyObject` modifies the appropriate variable in `globals()` from `LazyObject` to `dict` (in example above) and because this change is happening in the middle of the series of calls in `dict` constructor  the xonsh binary raises the error when try to call the object that replaced. This works when we run the code in Python but not in xonsh binary from Nuitka. I've made an issue in Nuitka - [899](https://github.com/Nuitka/Nuitka/issues/899) - with minimal example.

So back to xonsh code. To fix this problem and allow xonsh to be builded by Nuitka we should exclude `dict(some_lazy_object)` logic. We have luck and this logic just in one place (environ.py):
```python
ctx = dict(BASE_ENV)
```

If we replace this to the `BASE_ENV` value (I tested the startup speed and it had no changes):
```python
    ctx = {
        "BASH_COMPLETIONS": list(DEFAULT_VARS["BASH_COMPLETIONS"].default),
        "PROMPT_FIELDS": dict(DEFAULT_VARS["PROMPT_FIELDS"].default),
        "XONSH_VERSION": XONSH_VERSION,
    }
```
Then we can run immediately:
```bash
# I'm using Ubuntu so I will build on Ubuntu and test in Ubuntu docker container
python3 -O -m nuitka --python-flag=no_site --python-flag=no_warnings --standalone --follow-imports xonsh
# it takes around 1-2 hours on 8 cores
# the standalone xonsh binary will be in ./xonsh.dist
```
And then we could test standalone xonsh binary:
```bash
docker run -it --rm -v $PWD/xonsh.dist:/xsh ubuntu
cd /xsh
./xonsh
```
It works without any changes around amalgam or another chages of the code!

I've made a PR with the changes -

**Comment by anki-code** [comment]
JFYI The simpler recipe to build xonsh with Nuitka is here - https://github.com/Nuitka/Nuitka/issues/1401#issue-1118685121

**Comment by anki-code** [comment]
Just want to let you know that I'm playing with xonsh and Nuitka here:

# xonsh-binary

https://github.com/anki-code/xonsh-binary/blob/b814e93e67604247e69cbdef3730523b44cdf67b/xonsh-glibc-binary.Dockerfile#L25-L34

<details>

```

FROM ubuntu:20.04

ARG PYTHON_VER=3.11.14
ARG XONSH_VER=0.21.2

ENV PYTHON_VER=${PYTHON_VER}
ENV XONSH_VER=${XONSH_VER}

SHELL ["/bin/bash", "-c"]
RUN apt update && apt install -y curl git vim patchelf elfutils binutils-common binutils
RUN yes | bash -c "$(curl -L https://micro.mamba.pm/install.sh)"
RUN /root/.local/bin/micromamba shell init -s bash >> ~/.bashrc

WORKDIR /
RUN git clone -b $XONSH_VER https://github.com/xonsh/xonsh
RUN mkdir -p /result

RUN eval "$(/root/.local/bin/micromamba shell hook -s bash)" \
     && micromamba activate base \
     && micromamba install -y -c conda-forge libpython-static==$PYTHON_VER gcc ccache \
     && pip install xonsh[full] ujson pygments prompt_toolkit pyperclip \
     && xonsh -c '2+2' \
     && pip install git+https://github.com/Nuitka/Nuitka@factory \
     && nuitka --standalone --onefile --static-libpython=yes \
            --onefile-tempdir-spec='%TEMP%/onefile_%PID%_%TIME%' \
            --show-progress --show-scons --show-modules \
            --assume-yes-for-downloads --jobs=2 \
            --include-package=pip \
            --include-module=ujson \
            --include-package=pygments \
            --include-package=prompt_toolkit \
            --include-module=pyperclip \
            /root/micromamba/lib/python3.11/site-packages/xonsh

```

</details>

**Comment by anki-code** [comment]
> I have opened [Nuitka/Nuitka#650](https://github.com/Nuitka/Nuitka/issues/650)

@scopatz It was solved - https://github.com/Nuitka/Nuitka/issues/650#issuecomment-3665788696

**Comment by CyberReaper00** [comment]
I also agree with the fact that a static binary would be quite useful for people to use, so i made a "static" build by doing the following

**Installed nuitka locally (in the xonsh dir)**
- `pip install nuitka --target ./nuitka # i find locality easier to manage`
- `PYTHONPATH="/path/to/xonsh/clone" # this is because i installed it locally, no need if you have it global`

**Ran this command**
- `python3 -m nuitka --onefile --standalone --include-package=xonsh --output-dir=dist xonsh/`

In the end, the filesize came out to 12M and the only dependency remaining was musl itself, which is pretty good

I would also recommend installing `ccache` for faster build speeds

But i couldnt get the binary to be fully static, and i discovered that requires a `python3-static` package and that wasnt available on alpine and i really dont want to build that myself, i also tried building without the static verion of python and it did compile into a static executable but it was not functional and kept giving errors about "not being able to read imports"

But if someone does want to try building a fully static version with the `python3-static` package(or whatever it may be on your package manager) then i would assume the following is all you need to do

**set:** `LDFLAGS="-static -no-pie"`
**run:**
```
python3 -m nuitka --onefile --standalone --static-libpython=yes --prefer-source-code --nofollow-imports --include-package=xonsh --output-dir=dist xonsh/
```

**Comment by anki-code** [comment]
@CyberReaper00 thanks for sharing this! I tried to build xonsh with musl and static python in [xonsh-binary/xonsh-musl-binary](https://github.com/anki-code/xonsh-binary/blob/b814e93e67604247e69cbdef3730523b44cdf67b/xonsh-musl-binary.Dockerfile). Please take a look. I used [python-cmake-buildsystem](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem) for that and it worked in [0.18.2 build with 
xonsh-0.18.2-py3.10-musl.bin file](https://github.com/anki-code/xonsh-binary/releases/tag/0.18.2) and in [0.17.0 build](https://github.com/anki-code/xonsh-binary/releases/tag/0.17.0-12). After time this method of building stopped working but I believe it's just need to update the versions to make it work.

**Comment by CyberReaper00** [comment]
@anki-code why are you linking me a dockerfile my dude, i dont know how to use docker or any of these container programs and besides that i also dont know how to use cmake, if i need to automate something i just use sh/bash, these seem like nice things, but i cant spend the time learning all these things just to test them out - i have other things to do - sorry, hope you find a way to make them work though

**Comment by anki-code** [comment]
I can build xonsh bin successfully using:
* Github Actions Ubuntu + xonsh + Nuitka
* Github Actions Ubuntu + xonsh + Nuitka + Mamba

Need more testing the binary build. Comments are welcome!

### Github Actions config

Note! Building with `--onefile` has issue (described below) so for production experiments remove this option.

<details>

```yaml
name: Build xonsh bin on Nuitka

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  xonsh-binary-nuitka:
    if: github.repository_owner == 'anki-code'
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      PYTHON_VER: 3.11
      
    steps:
      - uses: actions/checkout@v6

      - name: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install packages from apt
        run: |
          uname -a
          sudo apt install -y curl git vim patchelf elfutils binutils-common binutils libffi-dev gcc ccache libpython3.11-dev


      - name: Activate mamba and install packages
        run: |
             pip install -U pip setuptools wheel certifi \
             && pip install '.[full]' ujson pygments prompt_toolkit pyperclip \
             && pip install xontrib-sh xontrib-prompt-starship \
             && pip install git+https://github.com/Nuitka/Nuitka@factory

      - name: Test xonsh
        run: |
             which xonsh \
             && xonsh --version \
             && xonsh -c 'xcontext'

      - name: Nuitka build
        continue-on-error: true
        run: |
             nuitka --version \
             && nuitka \
                  --standalone \
                  --onefile \
                  --static-libpython=yes \
                  --no-deployment-flag=self-execution \
                  --onefile-tempdir-spec='%TEMP%/onefile_%PID%_%TIME%' \
                  --show-progress \
                  --show-scons \
                  --show-modules \
                  --assume-yes-for-downloads \
                  --jobs=2 \
                  --include-package=pip \
                  --include-package=setuptools \
                  --include-package=wheel \
                  --include-package=certifi \
                  --include-package-data=certifi \
                  --include-module=ujson \
                  --include-package=pygments \
                  --include-package=prompt_toolkit \
                  --include-module=pyperclip \
                  --include-module=ctypes \
                  --include-package=ctypes \
                  /opt/hostedtoolcache/Python/3.11.14/x64/lib/python$PYTHON_VER/site-packages/xonsh

      - name: nuitka-crash-report.xml
        continue-on-error: true
        run: |
          [ -f nuitka-crash-report.xml ] && cat nuitka-crash-report.xml

      - name: Rename binary file
        continue-on-error: true
        run: |
          ls -lah xonsh.bin
          export XONSH_SHOW_TRACEBACK=1
          ./xonsh.bin --version
          ./xonsh.bin -c '2+2'
          ./xonsh.bin -c 'echo 123'
          ./xonsh.bin -c 'import json; json.loads("{}")'
          ./xonsh.bin -c 'print(@.imp.json.loads("{}"))'    
          ./xonsh.bin -c 'print(@.imp.json.loads($(echo "{}")))'

      - name: Get latest release upload URL
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput('upload_url', release.upload_url);
            core.setOutput('tag_name', release.tag_name);

      - name: Upload xonsh binary Nuitka to latest release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./xonsh.bin
          asset_name: xonsh.bin
          asset_content_type: application/x-executable
```

With mamba:

```yaml
name: Build xonsh bin on Mamba+Nuitka

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-appimage:
    if: github.repository_owner == 'anki-code'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      PYTHON_VER: 3.11
      
    steps:
      - uses: actions/checkout@v6

      - name: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install packages from apt
        run: |
          uname -a
          sudo apt install -y curl git vim patchelf elfutils binutils-common binutils libffi-dev

      - name: Install mamba
        run: |
          yes | bash -c "$(curl -L https://micro.mamba.pm/install.sh)"
          /home/runner/.local/bin/micromamba info

      - name: Activate mamba and install packages
        run: |
          eval "$(/home/runner/.local/bin/micromamba shell hook -s bash)" \
             && micromamba activate base \
             && micromamba install -y -c conda-forge libpython-static==$PYTHON_VER gcc ccache libffi \
             && pip install -U pip setuptools wheel certifi \
             && pip install '.[full]' ujson pygments prompt_toolkit pyperclip \
             && pip install xontrib-sh xontrib-prompt-starship \
             && pip install git+https://github.com/Nuitka/Nuitka@factory

      - name: Test xonsh
        run: |
          eval "$(/home/runner/.local/bin/micromamba shell hook -s bash)" \
             && micromamba activate base \
             && xonsh --version \
             && xonsh -c '21+21'

      - name: Nuitka build
        continue-on-error: true
        run: |
          eval "$(/home/runner/.local/bin/micromamba shell hook -s bash)" \
             && micromamba activate base \
             && nuitka --version \
             && nuitka \
                  --standalone \
                  --onefile \
                  --static-libpython=yes \
                  --no-deployment-flag=self-execution \
                  --onefile-tempdir-spec='%TEMP%/onefile_%PID%_%TIME%' \
                  --show-progress \
                  --show-scons \
                  --show-modules \
                  --assume-yes-for-downloads \
                  --jobs=2 \
                  --include-package=pip \
                  --include-package=setuptools \
                  --include-package=wheel \
                  --include-package=certifi \
                  --include-package-data=certifi \
                  --include-module=ujson \
                  --include-package=pygments \
                  --include-package=prompt_toolkit \
                  --include-module=pyperclip \
                  --include-module=ctypes \
                  --include-package=ctypes \
                  /home/runner/micromamba/lib/python$PYTHON_VER/site-packages/xonsh

      - name: nuitka-crash-report.xml
        continue-on-error: true
        run: |
          [ -f nuitka-crash-report.xml ] && cat nuitka-crash-report.xml

      - name: Rename binary file
        run: |
          ls -lah xonsh.bin
          export XONSH_SHOW_TRACEBACK=1
          ./xonsh.bin --version
          ./xonsh.bin -c '2+2'
          ./xonsh.bin -c 'echo 123'
          ./xonsh.bin -c 'print(@.imp.json.loads("{}"))'
          mv xonsh.bin xonsh-mamba.bin

      - name: Get latest release upload URL
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput('upload_url', release.upload_url);
            core.setOutput('tag_name', release.tag_name);

      - name: Upload xonsh mamba Nuitka to latest release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./xonsh-mamba.bin
          asset_name: xonsh-mamba.bin
          asset_content_type: application/x-executable
```

</details>

### Issue in case of building with `nuitka --onefile`

After build with `--onefile` I'm facing with issue (https://github.com/Nuitka/Nuitka/issues/3745) around running captured subprocess:

```xsh
# Pure xonsh run
./xonsh.bin --no-rc --no-env

echo 123
# 123
@.imp.json.loads('{}')
# {}

echo $(echo)
# [3]+  Stopped                 ./xonsh.bin --no-rc --no-env --shell-type readline -DCOLOR_INPUT=0 -DCOLOR_RESULTS=0 -DPROMPT='@ ' -DXONSH_HISTORY_BACKEND=dummy -DXONTRIBS_AUTOLOAD_DISABLED=1
```

Fix is do not using `--onefile` or may be ignoring SIGTTOU but we don't know consequences:
```xsh
trap '' TTOU
./xonsh.bin  # builded with `nuitka --onefile`
echo $(echo 123)
# 123
```
or
```xsh
./xonsh.bin  # builded with `nuitka --onefile`
@.imp.signal.signal(@.imp.signal.SIGTTOU, @.imp.signal.SIG_IGN)
echo $(echo 123)
# 123
```
